export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastro'
export { default as Agenda} from './Agenda'
export { default as Contato} from './Contato'
export { default as Sobre} from './Sobre'
export { default as Tarefa} from './Tarefa'
export { default as Home } from './Home'
export { default as Camera } from './Camera'
export { default as Map } from './Map'
export { default as File } from './File'